name: auth_api
description: A web server built using the shelf package.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.0.0
  crypt: ^4.0.1
  dotenv: ^3.0.0
  get_it: ^7.2.0
  hasura_connect: ^3.0.6
  injectable: ^1.5.0
  jaguar_jwt: ^3.0.0
  logger: ^1.1.0
  shelf: ^1.1.0
  shelf_router: ^1.1.2
  

dev_dependencies:
  build_runner: ^2.1.2
  injectable_generator: ^1.5.2
  shelf_router_generator: ^1.0.1
  pedantic: ^1.10.0
  
